service: chrome-on-lambda

provider:
  name: aws
  runtime: nodejs6.10
  profile: intercom-dev

plugins:
  - serverless-webpack

custom:
  webpackIncludeModules: false

functions:
  run:
    handler: src/chrome.run
    memorySize: 1536
    timeout: 300